### ISSUE TITLE
Newly seated player may not be able to play first hand

### ISSUE THREAD

**Issue by partition** [remotepoker/remotepoker#4]
Some explanation: https://poker.stackexchange.com/questions/5597/joining-and-rejoining-a-texas-holdem-poker-game-that-is-already-in-progress

**Comment by partition** [comment]
Look at `DealHandCommand` and its tests to start.

**Comment by molokoka** [comment]
After reading the explanation I've understood the next rules:
there are two types of "new" players: new(never played on this table before) and rejoined(temporary away player)

0) seat:
  a) new player can join on every free seat in the game;
  b) rejoined player has retained the seat, he can return only to his seat;
1) first hand after join/rejoin:
In case "new" player is meant to play as small blind without playing big blind in this round, the "new" player skips this hand. in other cases the "new" player can play a hand if meet the rules below:
a) new player pays big blind(or big + small ??) to enter the game;
b) rejoined player pays small blind if he missed small blind; pays big blind + small blind if he missed big blind (by missing big blind he misses small blind too because of rule 1) )
2) when player can leave/away: at any point of the game;

**Comment by partition** [comment]
Closing, 'good first issue' was probably an overstatement :D thanks a lot @molokoka
